### ISSUE TITLE
Add `react` and `react-dom`

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxlint-ecosystem-ci#14]

**Comment by yajatkaul** [comment]
i can add it can you please provide the repo in which you want to add it

**Comment by Boshen** [comment]
For react, read-dom and other transpiled and minified files, I want to have a list of files where you can get from a url (jsdelivr or github), and then run the linter over it to make sure it doesn't crash.

**Comment by Boshen** [comment]
So maybe have another json file, have CI read it and run oxlint on them one by one.
